/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Delmoro-Ke
 */
public class EncodingPane extends javax.swing.JPanel {

    /**
     * Creates new form EnrollmentPane
     */
    public EncodingPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInputs = new javax.swing.JPanel();
        panelStudentID = new javax.swing.JPanel();
        lblStudentID = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        panelStudentName = new javax.swing.JPanel();
        lblStudentName = new javax.swing.JLabel();
        comboStudentName = new javax.swing.JComboBox<>();
        separator = new javax.swing.JSeparator();
        panelSubjectCode = new javax.swing.JPanel();
        lblSubjectCode = new javax.swing.JLabel();
        comboSubjectCode = new javax.swing.JComboBox<>();
        panelSubjectDescription = new javax.swing.JPanel();
        lblSubjectDescription = new javax.swing.JLabel();
        comboSubjectDescription = new javax.swing.JComboBox<>();
        panelGrade = new javax.swing.JPanel();
        lblGrade = new javax.swing.JLabel();
        comboGrade = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new java.awt.GridBagLayout());

        panelInputs.setAlignmentX(0.0F);
        panelInputs.setAlignmentY(0.0F);
        panelInputs.setMaximumSize(new java.awt.Dimension(32767, 200));
        panelInputs.setMinimumSize(new java.awt.Dimension(365, 205));
        panelInputs.setName(""); // NOI18N
        panelInputs.setOpaque(false);
        panelInputs.setPreferredSize(new java.awt.Dimension(370, 200));
        panelInputs.setLayout(new javax.swing.BoxLayout(panelInputs, javax.swing.BoxLayout.Y_AXIS));

        panelStudentID.setOpaque(false);

        lblStudentID.setText("Student ID");
        lblStudentID.setMaximumSize(new java.awt.Dimension(110, 25));
        lblStudentID.setMinimumSize(new java.awt.Dimension(110, 25));
        lblStudentID.setPreferredSize(new java.awt.Dimension(110, 25));
        panelStudentID.add(lblStudentID);

        txtStudentID.setMaximumSize(new java.awt.Dimension(250, 30));
        txtStudentID.setMinimumSize(new java.awt.Dimension(250, 30));
        txtStudentID.setPreferredSize(new java.awt.Dimension(250, 30));
        txtStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentIDActionPerformed(evt);
            }
        });
        panelStudentID.add(txtStudentID);

        panelInputs.add(panelStudentID);

        panelStudentName.setOpaque(false);

        lblStudentName.setText("Student name");
        lblStudentName.setMaximumSize(new java.awt.Dimension(110, 25));
        lblStudentName.setMinimumSize(new java.awt.Dimension(110, 25));
        lblStudentName.setPreferredSize(new java.awt.Dimension(110, 25));
        panelStudentName.add(lblStudentName);

        comboStudentName.setMaximumSize(new java.awt.Dimension(250, 30));
        comboStudentName.setMinimumSize(new java.awt.Dimension(250, 30));
        comboStudentName.setName(""); // NOI18N
        comboStudentName.setPreferredSize(new java.awt.Dimension(250, 30));
        panelStudentName.add(comboStudentName);

        panelInputs.add(panelStudentName);

        separator.setForeground(new java.awt.Color(255, 255, 255));
        separator.setMaximumSize(new java.awt.Dimension(365, 5));
        separator.setMinimumSize(new java.awt.Dimension(365, 5));
        separator.setPreferredSize(new java.awt.Dimension(365, 5));
        panelInputs.add(separator);

        panelSubjectCode.setOpaque(false);

        lblSubjectCode.setText("Subject code");
        lblSubjectCode.setMaximumSize(new java.awt.Dimension(110, 25));
        lblSubjectCode.setMinimumSize(new java.awt.Dimension(110, 25));
        lblSubjectCode.setPreferredSize(new java.awt.Dimension(110, 25));
        panelSubjectCode.add(lblSubjectCode);

        comboSubjectCode.setMaximumSize(new java.awt.Dimension(250, 30));
        comboSubjectCode.setMinimumSize(new java.awt.Dimension(250, 30));
        comboSubjectCode.setName(""); // NOI18N
        comboSubjectCode.setPreferredSize(new java.awt.Dimension(250, 30));
        panelSubjectCode.add(comboSubjectCode);

        panelInputs.add(panelSubjectCode);

        panelSubjectDescription.setOpaque(false);

        lblSubjectDescription.setText("Subject description");
        lblSubjectDescription.setMaximumSize(new java.awt.Dimension(110, 25));
        lblSubjectDescription.setMinimumSize(new java.awt.Dimension(110, 25));
        lblSubjectDescription.setPreferredSize(new java.awt.Dimension(110, 25));
        panelSubjectDescription.add(lblSubjectDescription);

        comboSubjectDescription.setMaximumSize(new java.awt.Dimension(250, 30));
        comboSubjectDescription.setMinimumSize(new java.awt.Dimension(250, 30));
        comboSubjectDescription.setName(""); // NOI18N
        comboSubjectDescription.setPreferredSize(new java.awt.Dimension(250, 30));
        panelSubjectDescription.add(comboSubjectDescription);

        panelInputs.add(panelSubjectDescription);

        panelGrade.setOpaque(false);

        lblGrade.setText("Grade");
        lblGrade.setMaximumSize(new java.awt.Dimension(110, 25));
        lblGrade.setMinimumSize(new java.awt.Dimension(110, 25));
        lblGrade.setPreferredSize(new java.awt.Dimension(110, 25));
        panelGrade.add(lblGrade);

        comboGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.00", "1.25", "1.50", "1.75", "2.00", "2.25", "2.50", "2.75", "3.00", "5.00" }));
        comboGrade.setToolTipText("");
        comboGrade.setMaximumSize(new java.awt.Dimension(185, 30));
        comboGrade.setMinimumSize(new java.awt.Dimension(185, 30));
        comboGrade.setName(""); // NOI18N
        comboGrade.setPreferredSize(new java.awt.Dimension(185, 30));
        panelGrade.add(comboGrade);

        jButton1.setText("Save");
        jButton1.setMaximumSize(new java.awt.Dimension(60, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(60, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(60, 30));
        panelGrade.add(jButton1);

        panelInputs.add(panelGrade);

        add(panelInputs, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void txtStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboGrade;
    private javax.swing.JComboBox<String> comboStudentName;
    private javax.swing.JComboBox<String> comboSubjectCode;
    private javax.swing.JComboBox<String> comboSubjectDescription;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblSubjectCode;
    private javax.swing.JLabel lblSubjectDescription;
    private javax.swing.JPanel panelGrade;
    private javax.swing.JPanel panelInputs;
    private javax.swing.JPanel panelStudentID;
    private javax.swing.JPanel panelStudentName;
    private javax.swing.JPanel panelSubjectCode;
    private javax.swing.JPanel panelSubjectDescription;
    private javax.swing.JSeparator separator;
    private javax.swing.JTextField txtStudentID;
    // End of variables declaration//GEN-END:variables
}
