/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Delmoro-Ke
 */
public class EnrollmentPane extends javax.swing.JPanel {

    /**
     * Creates new form EnrollmentPane
     */
    public EnrollmentPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        textFieldPanel = new javax.swing.JPanel();
        studentIdPane = new javax.swing.JSplitPane();
        studentNamePane = new javax.swing.JSplitPane();
        coursePane = new javax.swing.JSplitPane();
        yearLevelPane = new javax.swing.JSplitPane();
        buttonPanel = new javax.swing.JPanel();

        textFieldPanel.setLayout(new javax.swing.BoxLayout(textFieldPanel, javax.swing.BoxLayout.Y_AXIS));
        textFieldPanel.add(studentIdPane);
        textFieldPanel.add(studentNamePane);
        textFieldPanel.add(coursePane);
        textFieldPanel.add(yearLevelPane);

        jSplitPane.setLeftComponent(textFieldPanel);
        jSplitPane.setRightComponent(buttonPanel);

        add(jSplitPane);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JSplitPane coursePane;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JSplitPane studentIdPane;
    private javax.swing.JSplitPane studentNamePane;
    private javax.swing.JPanel textFieldPanel;
    private javax.swing.JSplitPane yearLevelPane;
    // End of variables declaration//GEN-END:variables
}
