/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Classes.Student;
import Utilities.IntFilter;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;
import org.bson.Document;

/**
 *
 * @author Delmoro-Ke
 */
public class EnrollmentPane extends javax.swing.JPanel {
    boolean courseFilter;
    boolean yearLevelFilter;
    
    /**
     * Creates new form EnrollmentPane
     */
    public EnrollmentPane() {
        initComponents();
        ((AbstractDocument) txtStudentId.getDocument()).setDocumentFilter (new IntFilter());
        
        populateTable();
        courseFilter = false;
        yearLevelFilter = false;
    }
    
    private void insertStudent() {
        try (MongoClient client = MongoClients.create ("mongodb://localhost:27017")) {
            MongoDatabase db = client.getDatabase ("Enrollment");
            MongoCollection<Document> collection = db.getCollection("Student");
        
            Student student = new Student (
                Integer.valueOf(txtStudentId.getText()),
                txtStudentName.getText(),
                comboCourse.getSelectedItem().toString(),
                comboYearLevel.getSelectedIndex() + 1
            );
            
            collection.insertOne(student.toDocument());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tableInfo.getModel();
        model.setRowCount(0);
        
        try (MongoClient client = MongoClients.create ("mongodb://localhost:27017")) {
            MongoDatabase db = client.getDatabase ("Enrollment");          
            
            ArrayList<Student> students = Student.getStudents(db);
            for (Student s : students) {
                if (courseFilter && !s.getCourse().equals(comboCourse.getSelectedItem().toString()))
                    continue;
                if (yearLevelFilter && !s.getYearLevelString().equals(comboYearLevel.getSelectedItem().toString()))
                    continue;

                String[] row = new String[] {
                    Integer.toString(s.getStudentId()),
                    s.getStudentName(),
                    s.getCourse(),
                    s.getYearLevelString()
                };

                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInputs = new javax.swing.JPanel();
        panelStudentID = new javax.swing.JPanel();
        lblStudentID = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        panelStudentName = new javax.swing.JPanel();
        lblStudentName = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        panelCourse = new javax.swing.JPanel();
        lblCourse = new javax.swing.JLabel();
        comboCourse = new javax.swing.JComboBox<>();
        btnCourseFilter = new javax.swing.JButton();
        panelYearLevel = new javax.swing.JPanel();
        lblYearLevel = new javax.swing.JLabel();
        comboYearLevel = new javax.swing.JComboBox<>();
        btnYearLevelFilter = new javax.swing.JButton();
        scrollInfo = new javax.swing.JScrollPane();
        tableInfo = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 204, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        panelInputs.setMaximumSize(new java.awt.Dimension(32767, 160));
        panelInputs.setOpaque(false);
        panelInputs.setPreferredSize(new java.awt.Dimension(100, 160));
        panelInputs.setLayout(new javax.swing.BoxLayout(panelInputs, javax.swing.BoxLayout.Y_AXIS));

        panelStudentID.setOpaque(false);

        lblStudentID.setText("Student ID");
        lblStudentID.setMaximumSize(new java.awt.Dimension(100, 25));
        lblStudentID.setMinimumSize(new java.awt.Dimension(100, 25));
        lblStudentID.setPreferredSize(new java.awt.Dimension(100, 25));
        panelStudentID.add(lblStudentID);

        txtStudentId.setMaximumSize(new java.awt.Dimension(185, 30));
        txtStudentId.setMinimumSize(new java.awt.Dimension(185, 30));
        txtStudentId.setPreferredSize(new java.awt.Dimension(185, 30));
        panelStudentID.add(txtStudentId);

        btnAdd.setText("Add");
        btnAdd.setMaximumSize(new java.awt.Dimension(60, 30));
        btnAdd.setMinimumSize(new java.awt.Dimension(60, 30));
        btnAdd.setPreferredSize(new java.awt.Dimension(60, 30));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panelStudentID.add(btnAdd);

        panelInputs.add(panelStudentID);

        panelStudentName.setOpaque(false);

        lblStudentName.setText("Student name");
        lblStudentName.setMaximumSize(new java.awt.Dimension(100, 25));
        lblStudentName.setMinimumSize(new java.awt.Dimension(100, 25));
        lblStudentName.setPreferredSize(new java.awt.Dimension(100, 25));
        panelStudentName.add(lblStudentName);

        txtStudentName.setMaximumSize(new java.awt.Dimension(250, 30));
        txtStudentName.setMinimumSize(new java.awt.Dimension(250, 30));
        txtStudentName.setPreferredSize(new java.awt.Dimension(250, 30));
        panelStudentName.add(txtStudentName);

        panelInputs.add(panelStudentName);

        panelCourse.setOpaque(false);

        lblCourse.setText("Course");
        lblCourse.setMaximumSize(new java.awt.Dimension(100, 25));
        lblCourse.setMinimumSize(new java.awt.Dimension(100, 25));
        lblCourse.setPreferredSize(new java.awt.Dimension(100, 25));
        panelCourse.add(lblCourse);

        comboCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSIT", "BSCS", "BLIS" }));
        comboCourse.setMaximumSize(new java.awt.Dimension(185, 30));
        comboCourse.setMinimumSize(new java.awt.Dimension(185, 30));
        comboCourse.setName(""); // NOI18N
        comboCourse.setPreferredSize(new java.awt.Dimension(185, 30));
        comboCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCourseActionPerformed(evt);
            }
        });
        panelCourse.add(comboCourse);

        btnCourseFilter.setText("Filter");
        btnCourseFilter.setMaximumSize(new java.awt.Dimension(60, 30));
        btnCourseFilter.setMinimumSize(new java.awt.Dimension(60, 30));
        btnCourseFilter.setPreferredSize(new java.awt.Dimension(60, 30));
        btnCourseFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseFilterActionPerformed(evt);
            }
        });
        panelCourse.add(btnCourseFilter);

        panelInputs.add(panelCourse);

        panelYearLevel.setOpaque(false);

        lblYearLevel.setText("Year level");
        lblYearLevel.setMaximumSize(new java.awt.Dimension(100, 25));
        lblYearLevel.setMinimumSize(new java.awt.Dimension(100, 25));
        lblYearLevel.setPreferredSize(new java.awt.Dimension(100, 25));
        panelYearLevel.add(lblYearLevel);

        comboYearLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First year", "Second year", "Third year", "Fourth year", "Fifth year" }));
        comboYearLevel.setToolTipText("");
        comboYearLevel.setMaximumSize(new java.awt.Dimension(185, 30));
        comboYearLevel.setMinimumSize(new java.awt.Dimension(185, 30));
        comboYearLevel.setName(""); // NOI18N
        comboYearLevel.setPreferredSize(new java.awt.Dimension(185, 30));
        comboYearLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboYearLevelActionPerformed(evt);
            }
        });
        panelYearLevel.add(comboYearLevel);

        btnYearLevelFilter.setText("Filter");
        btnYearLevelFilter.setMaximumSize(new java.awt.Dimension(60, 30));
        btnYearLevelFilter.setMinimumSize(new java.awt.Dimension(60, 30));
        btnYearLevelFilter.setPreferredSize(new java.awt.Dimension(60, 30));
        btnYearLevelFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYearLevelFilterActionPerformed(evt);
            }
        });
        panelYearLevel.add(btnYearLevelFilter);

        panelInputs.add(panelYearLevel);

        add(panelInputs);

        tableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student name", "Course", "Year level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableInfo.getTableHeader().setReorderingAllowed(false);
        scrollInfo.setViewportView(tableInfo);

        add(scrollInfo);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseFilterActionPerformed
        courseFilter = !courseFilter;
        if (courseFilter)
            btnCourseFilter.setBackground(Color.YELLOW);
        else
            btnCourseFilter.setBackground(Color.WHITE);
        populateTable();
    }//GEN-LAST:event_btnCourseFilterActionPerformed

    private void btnYearLevelFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYearLevelFilterActionPerformed
        yearLevelFilter = !yearLevelFilter;
        if (yearLevelFilter)
            btnYearLevelFilter.setBackground(Color.YELLOW);
        else
            btnYearLevelFilter.setBackground(Color.WHITE);
        populateTable();
    }//GEN-LAST:event_btnYearLevelFilterActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        insertStudent();
        populateTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void comboCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCourseActionPerformed
        populateTable();
    }//GEN-LAST:event_comboCourseActionPerformed

    private void comboYearLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboYearLevelActionPerformed
        populateTable();
    }//GEN-LAST:event_comboYearLevelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCourseFilter;
    private javax.swing.JButton btnYearLevelFilter;
    private javax.swing.JComboBox<String> comboCourse;
    private javax.swing.JComboBox<String> comboYearLevel;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblYearLevel;
    private javax.swing.JPanel panelCourse;
    private javax.swing.JPanel panelInputs;
    private javax.swing.JPanel panelStudentID;
    private javax.swing.JPanel panelStudentName;
    private javax.swing.JPanel panelYearLevel;
    private javax.swing.JScrollPane scrollInfo;
    private javax.swing.JTable tableInfo;
    private javax.swing.JTextField txtStudentId;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}
