/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Classes.Enrollment;
import Classes.Student;
import Classes.Subject;
import Utilities.PopulateTable;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoDatabase;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Delmoro-Ke
 */
public class GradesPane extends javax.swing.JPanel {
    /**
     * Creates new form GradesPane
     */
    public GradesPane() {
        initComponents();
        populateCombo();
        PopulateTable.populateGradeTable(tableGrades, comboStudentName);
    }
    
    private void populateCombo() {
        Object curr = comboStudentName.getSelectedItem();
        comboStudentName.removeAllItems();
        comboStudentName.addItem(null);
        
        try (MongoClient client = MongoClients.create ("mongodb://localhost:27017")) {
            MongoDatabase db = client.getDatabase ("Enrollment");
            
            ArrayList<String> names = Student.getStudentNames(db);
            for (String name : names) {
                comboStudentName.addItem(name);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        comboStudentName.setSelectedItem(curr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelStudentName = new javax.swing.JPanel();
        lblStudentName = new javax.swing.JLabel();
        comboStudentName = new javax.swing.JComboBox<>();
        scrollGrades = new javax.swing.JScrollPane();
        tableGrades = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        panelStudentName.setMaximumSize(new java.awt.Dimension(32767, 40));
        panelStudentName.setMinimumSize(new java.awt.Dimension(339, 40));
        panelStudentName.setOpaque(false);
        panelStudentName.setPreferredSize(new java.awt.Dimension(539, 40));

        lblStudentName.setText("Student name");
        lblStudentName.setMaximumSize(new java.awt.Dimension(100, 25));
        lblStudentName.setMinimumSize(new java.awt.Dimension(100, 25));
        lblStudentName.setPreferredSize(new java.awt.Dimension(100, 25));
        panelStudentName.add(lblStudentName);

        comboStudentName.setMaximumSize(new java.awt.Dimension(250, 30));
        comboStudentName.setMinimumSize(new java.awt.Dimension(250, 30));
        comboStudentName.setName(""); // NOI18N
        comboStudentName.setPreferredSize(new java.awt.Dimension(250, 30));
        comboStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStudentNameActionPerformed(evt);
            }
        });
        panelStudentName.add(comboStudentName);

        add(panelStudentName);

        tableGrades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject code", "Description", "Units", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableGrades.getTableHeader().setReorderingAllowed(false);
        scrollGrades.setViewportView(tableGrades);

        add(scrollGrades);
    }// </editor-fold>//GEN-END:initComponents

    private void comboStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStudentNameActionPerformed
        populateCombo();
        PopulateTable.populateGradeTable(tableGrades, comboStudentName);
    }//GEN-LAST:event_comboStudentNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboStudentName;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JPanel panelStudentName;
    private javax.swing.JScrollPane scrollGrades;
    private javax.swing.JTable tableGrades;
    // End of variables declaration//GEN-END:variables
}
