/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Classes.*;
import Utilities.*;
import com.mongodb.client.*;
import java.util.ArrayList;
/**
 *
 * @author Delmoro-Ke
 */
public class GradesPanel extends javax.swing.JPanel {
    /**
     * Creates new form GradesPane
     */
    public GradesPanel() {
        initComponents();
        populateCombo();
        String name = comboStudentName.getSelectedItem() == null ? null : comboStudentName.getSelectedItem().toString();
        PopulateTable.grade(tableGrades, name);
    }
    
    private void populateCombo() {
        Object curr = comboStudentName.getSelectedItem();
        comboStudentName.removeAllItems();
        comboStudentName.addItem(null);
        
        try (MongoClient client = MongoClients.create ("mongodb://localhost:27017")) {
            MongoDatabase db = client.getDatabase ("Enrollment");
            
            ArrayList<String> names = Student.getStudentNames(db);
            for (String name : names) {
                comboStudentName.addItem(name);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        comboStudentName.setSelectedItem(curr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelStudentName = new javax.swing.JPanel();
        lblStudentName = new javax.swing.JLabel();
        comboStudentName = new javax.swing.JComboBox<>();
        panelGPA = new javax.swing.JPanel();
        lblGPA = new javax.swing.JLabel();
        scrollGrades = new javax.swing.JScrollPane();
        tableGrades = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        panelStudentName.setMaximumSize(new java.awt.Dimension(32767, 40));
        panelStudentName.setMinimumSize(new java.awt.Dimension(339, 40));
        panelStudentName.setOpaque(false);
        panelStudentName.setPreferredSize(new java.awt.Dimension(539, 40));

        lblStudentName.setText("Student name");
        lblStudentName.setMaximumSize(new java.awt.Dimension(100, 25));
        lblStudentName.setMinimumSize(new java.awt.Dimension(100, 25));
        lblStudentName.setPreferredSize(new java.awt.Dimension(100, 25));
        panelStudentName.add(lblStudentName);

        comboStudentName.setMaximumSize(new java.awt.Dimension(250, 30));
        comboStudentName.setMinimumSize(new java.awt.Dimension(250, 30));
        comboStudentName.setName(""); // NOI18N
        comboStudentName.setPreferredSize(new java.awt.Dimension(250, 30));
        comboStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStudentNameActionPerformed(evt);
            }
        });
        panelStudentName.add(comboStudentName);

        add(panelStudentName);

        panelGPA.setMaximumSize(new java.awt.Dimension(32767, 25));
        panelGPA.setMinimumSize(new java.awt.Dimension(339, 25));
        panelGPA.setOpaque(false);
        panelGPA.setPreferredSize(new java.awt.Dimension(539, 25));
        panelGPA.setLayout(new java.awt.GridLayout(1, 0));

        lblGPA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGPA.setText("General Percentile Average: N/A");
        lblGPA.setMaximumSize(new java.awt.Dimension(250, 25));
        lblGPA.setMinimumSize(new java.awt.Dimension(250, 25));
        lblGPA.setPreferredSize(new java.awt.Dimension(250, 25));
        panelGPA.add(lblGPA);

        add(panelGPA);

        tableGrades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject code", "Description", "Units", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableGrades.getTableHeader().setReorderingAllowed(false);
        scrollGrades.setViewportView(tableGrades);
        if (tableGrades.getColumnModel().getColumnCount() > 0) {
            tableGrades.getColumnModel().getColumn(0).setMinWidth(0);
            tableGrades.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableGrades.getColumnModel().getColumn(2).setMinWidth(0);
            tableGrades.getColumnModel().getColumn(2).setPreferredWidth(0);
            tableGrades.getColumnModel().getColumn(3).setMinWidth(0);
            tableGrades.getColumnModel().getColumn(3).setPreferredWidth(0);
        }

        add(scrollGrades);
    }// </editor-fold>//GEN-END:initComponents

    private void comboStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStudentNameActionPerformed
        populateCombo();
        String name = comboStudentName.getSelectedItem() == null ? null : comboStudentName.getSelectedItem().toString();
        PopulateTable.grade(tableGrades, name);
        double gpa = Calculate.GPA(name);
        lblGPA.setText("General Percentile Average: " + (gpa > 0 ? String.format("%.2f", gpa) : "N/A"));
    }//GEN-LAST:event_comboStudentNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboStudentName;
    private javax.swing.JLabel lblGPA;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JPanel panelGPA;
    private javax.swing.JPanel panelStudentName;
    private javax.swing.JScrollPane scrollGrades;
    private javax.swing.JTable tableGrades;
    // End of variables declaration//GEN-END:variables
}
