/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Delmoro-Ke
 */
public class GradesPane extends javax.swing.JPanel {

    /**
     * Creates new form GradesPane
     */
    public GradesPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelStudentName = new javax.swing.JPanel();
        lblStudentName = new javax.swing.JLabel();
        comboStudentName = new javax.swing.JComboBox<>();
        tableStudents = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        lblStudentName.setText("Student name");
        panelStudentName.add(lblStudentName);

        comboStudentName.setMinimumSize(new java.awt.Dimension(250, 22));
        comboStudentName.setName(""); // NOI18N
        comboStudentName.setPreferredSize(new java.awt.Dimension(250, 22));
        panelStudentName.add(comboStudentName);

        add(panelStudentName);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject code", "Description", "Units", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        tableStudents.setViewportView(jTable1);

        add(tableStudents);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboStudentName;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JPanel panelStudentName;
    private javax.swing.JScrollPane tableStudents;
    // End of variables declaration//GEN-END:variables
}
