/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Utilities.*;
import com.formdev.flatlaf.FlatIntelliJLaf;
import javax.swing.*;

/**
 *
 * @author Delmoro-Ke
 */
public class SchoolFrame extends javax.swing.JFrame {
    /**
     * Creates new form SchoolDB
     */
    public SchoolFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedSchool = new javax.swing.JTabbedPane();
        GradesPanel = new GUI.GradesPanel();
        EncodingPanel = new GUI.EncodingPanel();
        StudentPanel = new GUI.StudentPanel();
        SubjectPanel = new GUI.SubjectPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("School Grading System - Kenji A. Delmoro");
        setMinimumSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        tabbedSchool.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedSchoolStateChanged(evt);
            }
        });
        tabbedSchool.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabbedSchoolPropertyChange(evt);
            }
        });
        tabbedSchool.addTab("Grades", GradesPanel);
        tabbedSchool.addTab("Encoding", EncodingPanel);
        tabbedSchool.addTab("Student", StudentPanel);
        tabbedSchool.addTab("Subject", SubjectPanel);

        getContentPane().add(tabbedSchool);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabbedSchoolPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabbedSchoolPropertyChange
//        int selectedIndex = tabbedSchool.getSelectedIndex();
//        JPanel selectedPanel = (JPanel) tabbedSchool.getComponentAt(selectedIndex);
//        if (selectedPanel instanceof TabSwitchListener) {
//            ((TabSwitchListener) selectedPanel).onTabSwitch();
//        }
    }//GEN-LAST:event_tabbedSchoolPropertyChange

    private void tabbedSchoolStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedSchoolStateChanged
        int selectedIndex = tabbedSchool.getSelectedIndex();
        JPanel selectedPanel = (JPanel) tabbedSchool.getComponentAt(selectedIndex);
        if (selectedPanel instanceof TabSwitchListener) {
            ((TabSwitchListener) selectedPanel).onTabSwitch();
        }
    }//GEN-LAST:event_tabbedSchoolStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new SchoolFrame().setVisible(true);
                }
            });
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchoolFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("FlatLaf Light".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SchoolFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SchoolFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SchoolFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SchoolFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SchoolFrame().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.EncodingPanel EncodingPanel;
    private GUI.GradesPanel GradesPanel;
    private GUI.StudentPanel StudentPanel;
    private GUI.SubjectPanel SubjectPanel;
    private javax.swing.JTabbedPane tabbedSchool;
    // End of variables declaration//GEN-END:variables
}
