/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Classes.*;
import Utilities.*;
import com.mongodb.client.*;
import java.awt.Color;
import javax.swing.*;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author Delmoro-Ke
 */
public class StudentPanel extends javax.swing.JPanel {

    boolean courseFilter;
    boolean yearLevelFilter;

    /**
     * Creates new form EnrollmentPane
     */
    public StudentPanel() {
        initComponents();
        ((AbstractDocument) txtStudentId.getDocument()).setDocumentFilter(new StudentIDFilter());

        PopulateTable.student(tableInfo, courseFilter, comboCourse, yearLevelFilter, comboYearLevel);
        courseFilter = false;
        yearLevelFilter = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInputs = new javax.swing.JPanel();
        panelStudentID = new javax.swing.JPanel();
        lblStudentID = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        panelStudentName = new javax.swing.JPanel();
        lblStudentName = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        panelCourse = new javax.swing.JPanel();
        lblCourse = new javax.swing.JLabel();
        comboCourse = new javax.swing.JComboBox<>();
        btnCourseFilter = new javax.swing.JButton();
        panelYearLevel = new javax.swing.JPanel();
        lblYearLevel = new javax.swing.JLabel();
        comboYearLevel = new javax.swing.JComboBox<>();
        btnYearLevelFilter = new javax.swing.JButton();
        scrollInfo = new javax.swing.JScrollPane();
        tableInfo = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 204, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        panelInputs.setMaximumSize(new java.awt.Dimension(32767, 160));
        panelInputs.setOpaque(false);
        panelInputs.setPreferredSize(new java.awt.Dimension(100, 160));
        panelInputs.setLayout(new javax.swing.BoxLayout(panelInputs, javax.swing.BoxLayout.Y_AXIS));

        panelStudentID.setOpaque(false);

        lblStudentID.setText("Student ID");
        lblStudentID.setMaximumSize(new java.awt.Dimension(100, 25));
        lblStudentID.setMinimumSize(new java.awt.Dimension(100, 25));
        lblStudentID.setPreferredSize(new java.awt.Dimension(100, 25));
        panelStudentID.add(lblStudentID);

        txtStudentId.setMaximumSize(new java.awt.Dimension(185, 30));
        txtStudentId.setMinimumSize(new java.awt.Dimension(185, 30));
        txtStudentId.setPreferredSize(new java.awt.Dimension(185, 30));
        panelStudentID.add(txtStudentId);

        btnSave.setText("Save");
        btnSave.setMaximumSize(new java.awt.Dimension(60, 30));
        btnSave.setMinimumSize(new java.awt.Dimension(60, 30));
        btnSave.setPreferredSize(new java.awt.Dimension(60, 30));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        panelStudentID.add(btnSave);

        panelInputs.add(panelStudentID);

        panelStudentName.setOpaque(false);

        lblStudentName.setText("Student name");
        lblStudentName.setMaximumSize(new java.awt.Dimension(100, 25));
        lblStudentName.setMinimumSize(new java.awt.Dimension(100, 25));
        lblStudentName.setPreferredSize(new java.awt.Dimension(100, 25));
        panelStudentName.add(lblStudentName);

        txtStudentName.setMaximumSize(new java.awt.Dimension(250, 30));
        txtStudentName.setMinimumSize(new java.awt.Dimension(250, 30));
        txtStudentName.setPreferredSize(new java.awt.Dimension(250, 30));
        panelStudentName.add(txtStudentName);

        panelInputs.add(panelStudentName);

        panelCourse.setOpaque(false);

        lblCourse.setText("Course");
        lblCourse.setMaximumSize(new java.awt.Dimension(100, 25));
        lblCourse.setMinimumSize(new java.awt.Dimension(100, 25));
        lblCourse.setPreferredSize(new java.awt.Dimension(100, 25));
        panelCourse.add(lblCourse);

        comboCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSIT", "BSCS", "BLIS" }));
        comboCourse.setMaximumSize(new java.awt.Dimension(185, 30));
        comboCourse.setMinimumSize(new java.awt.Dimension(185, 30));
        comboCourse.setName(""); // NOI18N
        comboCourse.setPreferredSize(new java.awt.Dimension(185, 30));
        comboCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCourseActionPerformed(evt);
            }
        });
        panelCourse.add(comboCourse);

        btnCourseFilter.setText("Filter");
        btnCourseFilter.setMaximumSize(new java.awt.Dimension(60, 30));
        btnCourseFilter.setMinimumSize(new java.awt.Dimension(60, 30));
        btnCourseFilter.setPreferredSize(new java.awt.Dimension(60, 30));
        btnCourseFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseFilterActionPerformed(evt);
            }
        });
        panelCourse.add(btnCourseFilter);

        panelInputs.add(panelCourse);

        panelYearLevel.setOpaque(false);

        lblYearLevel.setText("Year level");
        lblYearLevel.setMaximumSize(new java.awt.Dimension(100, 25));
        lblYearLevel.setMinimumSize(new java.awt.Dimension(100, 25));
        lblYearLevel.setPreferredSize(new java.awt.Dimension(100, 25));
        panelYearLevel.add(lblYearLevel);

        comboYearLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First year", "Second year", "Third year", "Fourth year", "Fifth year" }));
        comboYearLevel.setToolTipText("");
        comboYearLevel.setMaximumSize(new java.awt.Dimension(185, 30));
        comboYearLevel.setMinimumSize(new java.awt.Dimension(185, 30));
        comboYearLevel.setName(""); // NOI18N
        comboYearLevel.setPreferredSize(new java.awt.Dimension(185, 30));
        comboYearLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboYearLevelActionPerformed(evt);
            }
        });
        panelYearLevel.add(comboYearLevel);

        btnYearLevelFilter.setText("Filter");
        btnYearLevelFilter.setMaximumSize(new java.awt.Dimension(60, 30));
        btnYearLevelFilter.setMinimumSize(new java.awt.Dimension(60, 30));
        btnYearLevelFilter.setPreferredSize(new java.awt.Dimension(60, 30));
        btnYearLevelFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYearLevelFilterActionPerformed(evt);
            }
        });
        panelYearLevel.add(btnYearLevelFilter);

        panelInputs.add(panelYearLevel);

        add(panelInputs);

        tableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student name", "Course", "Year level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableInfo.getTableHeader().setReorderingAllowed(false);
        scrollInfo.setViewportView(tableInfo);
        if (tableInfo.getColumnModel().getColumnCount() > 0) {
            tableInfo.getColumnModel().getColumn(0).setMinWidth(0);
            tableInfo.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableInfo.getColumnModel().getColumn(2).setMinWidth(0);
            tableInfo.getColumnModel().getColumn(2).setPreferredWidth(0);
            tableInfo.getColumnModel().getColumn(3).setMinWidth(0);
            tableInfo.getColumnModel().getColumn(3).setPreferredWidth(0);
        }

        add(scrollInfo);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseFilterActionPerformed
        courseFilter = !courseFilter;
        if (courseFilter) {
            btnCourseFilter.setBackground(Color.YELLOW);
        } else {
            btnCourseFilter.setBackground(Color.WHITE);
        }
        PopulateTable.student(tableInfo, courseFilter, comboCourse, yearLevelFilter, comboYearLevel);
    }//GEN-LAST:event_btnCourseFilterActionPerformed

    private void btnYearLevelFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYearLevelFilterActionPerformed
        yearLevelFilter = !yearLevelFilter;
        if (yearLevelFilter) {
            btnYearLevelFilter.setBackground(Color.YELLOW);
        } else {
            btnYearLevelFilter.setBackground(Color.WHITE);
        }
        PopulateTable.student(tableInfo, courseFilter, comboCourse, yearLevelFilter, comboYearLevel);
    }//GEN-LAST:event_btnYearLevelFilterActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtStudentId.getText().isBlank() || txtStudentName.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Missing info!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (MongoClient client = MongoClients.create("mongodb://localhost:27017")) {
            MongoDatabase db = client.getDatabase("Enrollment");

            Student student = new Student(
                    Integer.valueOf(txtStudentId.getText().trim()),
                    txtStudentName.getText().trim(),
                    comboCourse.getSelectedItem().toString(),
                    comboYearLevel.getSelectedIndex() + 1
            );

            student.addStudent(db);
        } catch (Exception e) {
            e.printStackTrace();
        }
        PopulateTable.student(tableInfo, courseFilter, comboCourse, yearLevelFilter, comboYearLevel);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void comboCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCourseActionPerformed
        PopulateTable.student(tableInfo, courseFilter, comboCourse, yearLevelFilter, comboYearLevel);
    }//GEN-LAST:event_comboCourseActionPerformed

    private void comboYearLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboYearLevelActionPerformed
        PopulateTable.student(tableInfo, courseFilter, comboCourse, yearLevelFilter, comboYearLevel);
    }//GEN-LAST:event_comboYearLevelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseFilter;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnYearLevelFilter;
    private javax.swing.JComboBox<String> comboCourse;
    private javax.swing.JComboBox<String> comboYearLevel;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblYearLevel;
    private javax.swing.JPanel panelCourse;
    private javax.swing.JPanel panelInputs;
    private javax.swing.JPanel panelStudentID;
    private javax.swing.JPanel panelStudentName;
    private javax.swing.JPanel panelYearLevel;
    private javax.swing.JScrollPane scrollInfo;
    private javax.swing.JTable tableInfo;
    private javax.swing.JTextField txtStudentId;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}
