/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college;

import java.util.Enumeration;
import java.util.Vector;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Delmoro-Ke
 */
public class CollegeFrame extends javax.swing.JFrame {
    College college;
    
    /**
     * Creates new form CollegeFrame
     */
    public CollegeFrame() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        grpBtnCollege = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbtnBusiness = new javax.swing.JRadioButton();
        rbtnEducation = new javax.swing.JRadioButton();
        rbtnMedical = new javax.swing.JRadioButton();
        rbtnEngineering = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFees = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTotalStudents = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtPrograms = new javax.swing.JTextField();
        txtCollegeName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        grpBtnCollege.add(rbtnBusiness);
        rbtnBusiness.setText("Business College");
        rbtnBusiness.setToolTipText("");
        rbtnBusiness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnBusinessActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnBusiness);

        grpBtnCollege.add(rbtnEducation);
        rbtnEducation.setText("Education College");
        rbtnEducation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEducationActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnEducation);

        grpBtnCollege.add(rbtnMedical);
        rbtnMedical.setText("Medical College");
        rbtnMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMedicalActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnMedical);

        grpBtnCollege.add(rbtnEngineering);
        rbtnEngineering.setText("Engineering College");
        rbtnEngineering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEngineeringActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnEngineering);

        tblFees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fees", "Rate", "Total Fee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFees);
        if (tblFees.getColumnModel().getColumnCount() > 0) {
            tblFees.getColumnModel().getColumn(0).setPreferredWidth(250);
        }

        jLabel1.setText("Total enrolees");
        jPanel2.add(jLabel1);

        txtTotalStudents.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTotalStudents.setPreferredSize(new java.awt.Dimension(125, 30));
        txtTotalStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalStudentsActionPerformed(evt);
            }
        });
        jPanel2.add(txtTotalStudents);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(1, 20));
        jPanel2.add(jSeparator1);

        jLabel2.setText("Number of programs");
        jPanel2.add(jLabel2);

        txtPrograms.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPrograms.setPreferredSize(new java.awt.Dimension(125, 30));
        txtPrograms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProgramsActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrograms);

        txtCollegeName.setText("College");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtCollegeName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCollegeName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void rbtnBusinessActionPerformed(java.awt.event.ActionEvent evt) {                                             
        listFees();
    }                                            

    private void rbtnEducationActionPerformed(java.awt.event.ActionEvent evt) {                                              
        listFees();
    }                                             
    
    private void rbtnEngineeringActionPerformed(java.awt.event.ActionEvent evt) {                                                
        listFees();
    }                                               

    private void rbtnMedicalActionPerformed(java.awt.event.ActionEvent evt) {                                            
        listFees();
    }                                           

    private void txtTotalStudentsActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        listFees();
    }                                                

    private void txtProgramsActionPerformed(java.awt.event.ActionEvent evt) {                                            
        listFees();
    }                                           

    private void listFees() {
        if (txtTotalStudents.getText().isEmpty() || txtPrograms.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter total enrolees and number of programs.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        DefaultTableModel mFee = (DefaultTableModel) this.tblFees.getModel();
        String action = "";
        for (Enumeration<AbstractButton> buttons = grpBtnCollege.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                action = button.getText();
                break;
            }
        }
        mFee.setRowCount(0);
        Vector v;
        
        switch (action) {
            case "Business College": 
                college = new BusinessCollege (
                    "College of Business and Administration",
                    Integer.parseInt(txtTotalStudents.getText()),
                    Integer.parseInt(txtPrograms.getText())
                );
                break;
            case "Education College": 
                college = new EducationCollege (
                    "College of Education",
                    Integer.parseInt(txtTotalStudents.getText()),
                    Integer.parseInt(txtPrograms.getText())
                );
                break;
            case "Medical College": 
                college = new MedicalCollege (
                    "College of Arts and Sciences",
                    Integer.parseInt(txtTotalStudents.getText()),
                    Integer.parseInt(txtPrograms.getText())
                );
                break;
            case "Engineering College": 
                college = new EngineeringCollege (
                    "College of Engineering, Architecture and Computing",
                    Integer.parseInt(txtTotalStudents.getText()),
                    Integer.parseInt(txtPrograms.getText())
                );
                break;
        }

        for (int i = 0; i < college.getFees().size(); i++) {
            Fee f = college.getFees().get(i);
            
            v = new Vector();
            v.add (f.getFee());
            v.add (String.format("%,.2f", f.getRate()));
            v.add (String.format("%,.2f", f.calculateFee(Integer.parseInt(txtTotalStudents.getText()))));
            mFee.addRow (v);
        }
        
        txtCollegeName.setText(college.getCollegeName());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CollegeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CollegeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CollegeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CollegeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CollegeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup grpBtnCollege;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbtnBusiness;
    private javax.swing.JRadioButton rbtnEducation;
    private javax.swing.JRadioButton rbtnEngineering;
    private javax.swing.JRadioButton rbtnMedical;
    private javax.swing.JTable tblFees;
    private javax.swing.JLabel txtCollegeName;
    private javax.swing.JTextField txtPrograms;
    private javax.swing.JTextField txtTotalStudents;
    // End of variables declaration                   
}
